apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opsguardian
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/omerbeithalahmy/ops-guardian.git
    targetRevision: HEAD
    path: charts/opsguardian
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true